install cat  log

diff --git a/install b/install
--- a/install
+++ b/install
@@ -37,7 +37,7 @@ function do_then_sudo
 function failed
 {
     echo "FAILED."
-    echo "[_/_] LOG OUTPUT:"
+    echo "[_/_] Log output from $logfile:"
     cat $logfile
     exit 1
 }
@@ -51,26 +51,26 @@ silent_trun rm -rf $DIR
 
 echo -n "[1/5] Downloading... "
 silent_run curl -o $FILE -L $URL
-[ $? == 0 ] && echo "done." || failed
+[ $? == 0 ] && echo "done." || { failed; exit 1; }
 
 tar xzf $FILE && cd $DIR
 mkdir build && cd build
 
 echo -n "[2/5] Configuring... "
 silent_run cmake ..
-[ $? == 0 ] && echo "done." || failed
+[ $? == 0 ] && echo "done." || { failed; exit 1; }
 
 echo -n "[3/5] Compiling... "
 silent_run make
-[ $? == 0 ] && echo "done." || failed
+[ $? == 0 ] && echo "done." || { failed; exit 1; }
 
 echo -n "[4/5] Testing... "
 silent_run make test
-[ $? == 0 ] && echo "done." || failed
+[ $? == 0 ] && echo "done." || { failed; exit 1; }
 
 echo -n "[5/5] Installing... "
 silent_run do_then_sudo make install
-[ $? == 0 ] && echo "done." || failed
+[ $? == 0 ] && echo "done." || { failed; exit 1; }
 
 rm "$logfile" || true
 
